project:
  type: book

book:
  title: "Event Based Models for Disease Progression"
  author: "Hongtao Hao & Joseph Austerweil"
  date: "10/13/2024"
  chapters:
    - index.md
    - 02_ebmExplain.ipynb
    - 03_gen.ipynb
    - 04_estDistParams.ipynb
    - 05_estStages.ipynb
    - 06_estS.ipynb
    - 07_hardKMeans.ipynb
    - 08_softKMeans.ipynb
    - 09_conjugatePriors.ipynb
    - 10_aggResults.ipynb
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    lightbox: true
  pdf:
    documentclass: scrreprt



